//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Numeros_Geneticos.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseSeed {
            get {
                return ((bool)(this["UseSeed"]));
            }
            set {
                this["UseSeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("27121995")]
        public int Seed {
            get {
                return ((int)(this["Seed"]));
            }
            set {
                this["Seed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int IndividualsPerGeneration {
            get {
                return ((int)(this["IndividualsPerGeneration"]));
            }
            set {
                this["IndividualsPerGeneration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int SelectionsByElitism {
            get {
                return ((int)(this["SelectionsByElitism"]));
            }
            set {
                this["SelectionsByElitism"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int MaxTotalGenerations {
            get {
                return ((int)(this["MaxTotalGenerations"]));
            }
            set {
                this["MaxTotalGenerations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int TotalChromosomes {
            get {
                return ((int)(this["TotalChromosomes"]));
            }
            set {
                this["TotalChromosomes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int SecondaryMutationChromosomesAmount {
            get {
                return ((int)(this["SecondaryMutationChromosomesAmount"]));
            }
            set {
                this["SecondaryMutationChromosomesAmount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int InitialNumberChromosomesAmount {
            get {
                return ((int)(this["InitialNumberChromosomesAmount"]));
            }
            set {
                this["InitialNumberChromosomesAmount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.7")]
        public float ElitismChromosomeChance {
            get {
                return ((float)(this["ElitismChromosomeChance"]));
            }
            set {
                this["ElitismChromosomeChance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public float MutationChance {
            get {
                return ((float)(this["MutationChance"]));
            }
            set {
                this["MutationChance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int MaxMutableChromosomes {
            get {
                return ((int)(this["MaxMutableChromosomes"]));
            }
            set {
                this["MaxMutableChromosomes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int ChromosomesMatchesToConcludeSimilar {
            get {
                return ((int)(this["ChromosomesMatchesToConcludeSimilar"]));
            }
            set {
                this["ChromosomesMatchesToConcludeSimilar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int SimilarAmountToConcludeUniformity {
            get {
                return ((int)(this["SimilarAmountToConcludeUniformity"]));
            }
            set {
                this["SimilarAmountToConcludeUniformity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int TargetNumber {
            get {
                return ((int)(this["TargetNumber"]));
            }
            set {
                this["TargetNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PriorityReproductionInsteadOfGuaranteedSurvival {
            get {
                return ((bool)(this["PriorityReproductionInsteadOfGuaranteedSurvival"]));
            }
            set {
                this["PriorityReproductionInsteadOfGuaranteedSurvival"] = value;
            }
        }
    }
}
